version: '3'
services:
  subliminal-server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      PACKWIZ_URL: "https://raw.githubusercontent.com/mxxntype/Subliminal/main/pack.toml"

      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      ENABLE_AUTOPAUSE: "true"

      MODE: "survival"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "8"
      MOTD: "Packwiz + Docker | Forge 1.19.2"

      ONLINE_MODE: "false"
      # ENABLE_WHITELIST: "true"
      # WHITELIST: |
      #   mxxntype
      # OPS: |
      #   mxxntype

      RCON_CMDS_STARTUP: |-
        /team add New
        /team add Old
        /gamerule randomTickSpeed 9
        /whitelist on
        /whitelist add mxxtype
        /op mxxntype
      RCON_CMDS_ON_CONNECT: |-
        /team join New @a[team=]
        /clear @a[team=New]
        /team join Old @a[team=New]

