name = "Subliminal"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "778d2f9a6a6d6697387bbebd51fb7f3541e660249b2fb03a2c567da5e8716e47"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
