name = "Subliminal"
author = "mxxntype"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92df60d35984f37bc7a39d405aa1f3a559e3a0a2e483d41055a407409a732640"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
