name = "Subliminal"
author = "mxxntype"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae0fbf8acccce9c9516057f53afd653e79d0e233db03aaffbb53d5fbc7a91a55"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
