name = "Subliminal"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "933787bc3785ac1bbe7719b0aba780c950e63d76e8d7efa4a9fe8376788ac340"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
