name = "Subliminal"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03fcd492f7e605405c9a24eb040d21deed65c47e759aa1adb83fdc15c6d6adf7"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
