name = "Subliminal"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d8ab28a119d5778378bdb07759580ff868affb305c3f7407306210c82f53c6"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
