name = "Subliminal"
author = "mxxntype"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e8f819d9addc6ed31a470bc6bb7ca95e508db3f6f65904983e19c6c019c4d9d"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
